Repository Kuzuru/notifier-bot, pull requests merged in 2022-10, with the labels that each got.

#11 Добавлена команда Clear
  src/main/java/urfu/Main.java
  src/main/java/urfu/core/commands/ClearCommand.java
  src/main/java/urfu/core/commands/HelpCommand.java
  src/main/java/urfu/core/commands/QuitCommand.java
  src/main/java/urfu/core/commands/VersionCommand.java
  src/main/java/urfu/core/commands/init/CommandInitializer.java
Labels: 🚀 Enhancement

#12 Feat/tests coverage
  src/test/java/urfu/core/commands/HelpCommandTest.java
  src/test/java/urfu/core/commands/QuitCommandTest.java
  src/test/java/urfu/core/commands/VersionCommandTest.java
Labels: ✏️ Tests Needed

#13 Добавлены первые тесты
  src/test/java/urfu/core/commands/HelpCommandTest.java
  src/test/java/urfu/core/commands/QuitCommandTest.java
  src/test/java/urfu/core/commands/VersionCommandTest.java
Labels: ✏️ Tests Needed

#14 Добавлен CI для Google Java Format
  .github/workflows/refofmat-code.yaml
  src/main/java/urfu/core/commands/ClearCommand.java
  src/main/java/urfu/core/commands/HelpCommand.java
  src/main/java/urfu/core/commands/QuitCommand.java
  src/main/java/urfu/core/commands/VersionCommand.java
  src/test/java/urfu/core/commands/HelpCommandTest.java
  src/test/java/urfu/core/commands/QuitCommandTest.java
  src/test/java/urfu/core/commands/VersionCommandTest.java
Labels: 🚀 Enhancement, 🛠 Wontfix

#15 Исправлено наименование переменных
  src/main/java/urfu/core/commands/HelpCommand.java
  src/main/java/urfu/core/commands/init/CommandInitializer.java
Labels: 🛠 Wontfix
